import { StyleSheet } from 'react-native';
import { C } from '../../../constants/colors';

// Styles extracted verbatim from WordWeave.tsx. No changes.
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#05060E',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 16,
    alignItems: 'center',
  },
  nebulaLayer: {
    position: 'absolute',
    top: -20,
    left: -40,
    right: -40,
    bottom: -20,
  },
  topGlow: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 240,
  },
  bgGlyph: {
    position: 'absolute',
    fontSize: 260,
    fontWeight: '900',
    color: '#EDE9E0',
    letterSpacing: -8,
  },
  bgGlyphFar: {
    position: 'absolute',
    fontSize: 140,
    fontWeight: '900',
    color: '#C8B4FF',
    letterSpacing: -4,
  },

  // Tap comet — flies from letter to word bar
  tapComet: {
    position: 'absolute',
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#FFE8B0',
    shadowColor: '#F0B542',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 8,
  },

  // Letter echo — ghost copy of a used letter
  letterEcho: {
    position: 'absolute',
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1.5,
    borderColor: 'rgba(240,181,66,0.6)',
    backgroundColor: 'rgba(240,181,66,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  letterEchoText: {
    color: '#FFE8B0',
    fontSize: 18,
    fontWeight: '900',
    textShadowColor: 'rgba(240,181,66,0.6)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },

  // Mega chromatic flash (6+ letter words)
  megaFlashWrap: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 90,
  },
  megaFlashText: {
    position: 'absolute',
    fontSize: 76,
    fontWeight: '900',
    letterSpacing: 3,
    textShadowColor: 'rgba(255,232,176,0.85)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 38,
  },
  megaFlashCore: {
    color: '#FFE8B0',
  },

  // Confetti origin — fires from the word bar area downward
  confettiOrigin: {
    position: 'absolute',
    top: 220,
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 95,
  },

  // Screen-wide white flash
  screenFlash: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#FFFFFF',
    zIndex: 88,
  },

  // Tier label
  tierLabelWrap: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 92,
  },
  tierLabelText: {
    fontSize: 88,
    fontWeight: '900',
    letterSpacing: 4,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 42,
  },

  // Submit button wrap + glow
  submitWrap: {
    flex: 1,
    position: 'relative',
  },
  submitGlow: {
    position: 'absolute',
    top: -6,
    left: -6,
    right: -6,
    bottom: -6,
    borderRadius: 22,
    backgroundColor: 'rgba(125,211,168,0.45)',
    shadowColor: '#7DD3A8',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 18,
    elevation: 10,
  },

  // Pressure ring — coral pulse around the orbit during finale
  pressureRing: {
    position: 'absolute',
    width: 290,
    height: 290,
    borderRadius: 145,
    borderWidth: 5,
    borderColor: 'rgba(232,112,126,0.95)',
    shadowColor: '#E8707E',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 34,
    elevation: 16,
  },

  // Score trail — ghost +N flying from word bar to score pill
  scoreTrail: {
    position: 'absolute',
    top: 0,
    left: 0,
    fontSize: 24,
    fontWeight: '900',
    color: C.peach,
    textShadowColor: 'rgba(224,155,107,0.8)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 14,
    zIndex: 80,
  },

  // Bonus sparkle — gold ring expanding from bonus letter
  bonusSparkle: {
    position: 'absolute',
    width: 58,
    height: 58,
    borderRadius: 29,
    borderWidth: 2,
    borderColor: 'rgba(255,220,120,0.9)',
    backgroundColor: 'rgba(255,220,120,0.15)',
    shadowColor: '#FFE08C',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 16,
    elevation: 10,
  },

  // Header
  header: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    marginTop: 4,
  },
  pill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  pillDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  pillText: {
    color: C.t1,
    fontSize: 14,
    fontWeight: '800',
  },
  pillLabel: {
    color: C.t3,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginLeft: 2,
  },

  timerWrap: {
    alignItems: 'center',
  },
  timerDigits: {
    color: C.t1,
    fontSize: 28,
    fontWeight: '900',
    letterSpacing: -1,
    lineHeight: 30,
  },
  timerDigitsFinal: {
    textShadowColor: 'rgba(232,112,126,0.6)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 14,
  },
  timerUnit: {
    color: C.t3,
    fontSize: 9,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    marginTop: -2,
  },

  // Timer bar
  timerBar: {
    width: '100%',
    height: 4,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderRadius: 2,
    overflow: 'hidden',
    marginBottom: 12,
  },
  timerFill: {
    height: '100%',
    borderRadius: 2,
  },

  // Combo
  comboSlot: {
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    marginBottom: 4,
  },
  comboBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 5,
    borderRadius: 999,
    borderWidth: 1.5,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.7,
    shadowRadius: 10,
    elevation: 6,
  },
  comboBadgeCount: {
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: 0.3,
  },
  comboBadgeLabel: {
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1.2,
  },

  // Word bar
  wordBarSlot: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  wordBarGlow: {
    position: 'absolute',
    top: -6,
    left: -6,
    right: -6,
    bottom: -6,
    borderRadius: 22,
    backgroundColor: 'rgba(125,211,168,0.35)',
  },
  wordBar: {
    width: '100%',
    borderRadius: 18,
    paddingVertical: 18,
    paddingHorizontal: 20,
    minHeight: 62,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(240,181,66,0.28)',
    overflow: 'hidden',
  },
  wordBarPlaceholder: {
    color: C.t3,
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0.3,
  },
  wordBarLetters: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  wordBarLetter: {
    color: '#FFE8B0',
    fontSize: 26,
    fontWeight: '900',
    letterSpacing: 3,
    textShadowColor: 'rgba(240,181,66,0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },

  // Feedback
  feedbackContainer: {
    height: 22,
    marginTop: 6,
    justifyContent: 'center',
  },
  feedbackText: {
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  feedbackValid: {
    color: C.green,
  },
  feedbackInvalid: {
    color: C.coral,
  },
  feedbackNearMiss: {
    color: C.amber,
  },

  // Orbit
  orbitContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 6,
  },
  orbit: {
    width: 270,
    height: 270,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  orbitRing: {
    position: 'absolute',
    width: 236,
    height: 236,
    borderRadius: 118,
    borderWidth: 1,
  },
  orbitTick: {
    position: 'absolute',
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  centerDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(240,181,66,0.28)',
  },

  discWrap: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  discHalo: {
    position: 'absolute',
    width: 72,
    height: 72,
    borderRadius: 36,
  },
  discInner: {
    width: 54,
    height: 54,
    borderRadius: 27,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    shadowOffset: { width: 0, height: 3 },
    overflow: 'hidden',
    elevation: 6,
  },
  discLetter: {
    fontSize: 20,
    fontWeight: '900',
    letterSpacing: 0.5,
    textShadowOffset: { width: 0, height: 0 },
  },

  floatScore: {
    position: 'absolute',
    color: C.amber,
    fontSize: 22,
    fontWeight: '900',
    textShadowColor: 'rgba(240,181,66,0.6)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  floatScoreBig: {
    fontSize: 34,
    color: '#FFE8B0',
    textShadowColor: 'rgba(255,232,176,0.8)',
    textShadowRadius: 18,
  },

  megaRing: {
    position: 'absolute',
    width: 200,
    height: 200,
    borderRadius: 100,
    borderWidth: 3,
    borderColor: C.amber,
    shadowColor: C.amber,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 20,
    elevation: 10,
  },

  // Actions
  actions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 12,
    width: '100%',
  },
  iconBtn: {
    paddingHorizontal: 18,
    paddingVertical: 15,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.04)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    minWidth: 64,
  },
  iconBtnText: {
    color: C.t2,
    fontSize: 15,
    fontWeight: '800',
  },
  submitBtn: {
    flex: 1,
    borderRadius: 16,
    paddingVertical: 15,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    shadowColor: '#6ECF9A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 6,
  },
  btnDisabled: {
    opacity: 0.55,
    shadowOpacity: 0,
  },
  submitText: {
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: 0.3,
  },

  // Recent words
  recentWords: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 12,
    justifyContent: 'center',
    minHeight: 28,
  },
  stamp: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    backgroundColor: 'rgba(155,114,224,0.10)',
    borderWidth: 1,
    borderColor: 'rgba(155,114,224,0.25)',
  },
  stampWord: {
    color: C.t1,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  stampPoints: {
    color: C.peach,
    fontSize: 10,
    fontWeight: '900',
  },

  // First-play hint
  hintCard: {
    position: 'absolute',
    bottom: 130,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: 'rgba(10,12,24,0.95)',
    borderWidth: 1,
    borderColor: 'rgba(240,181,66,0.4)',
    shadowColor: C.amber,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 8,
  },
  hintDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: C.amber,
  },
  hintText: {
    color: C.t1,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.3,
  },

  // Overlays (intro/outro)
  overlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
  },

  // Intro — clean centered layout
  introCenter: {
    alignItems: 'center',
    gap: 16,
  },
  introTitle: {
    color: '#FFE8B0',
    fontSize: 46,
    fontWeight: '900',
    letterSpacing: -0.5,
    textShadowColor: 'rgba(240,181,66,0.7)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 22,
  },
  introSub: {
    color: C.t2,
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
    letterSpacing: 0.4,
  },
  introGo: {
    fontSize: 56,
    fontWeight: '900',
    color: C.green,
    letterSpacing: 4,
    marginTop: 12,
    textShadowColor: 'rgba(125,211,168,0.8)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 22,
  },

  // Outro card
  outroCard: {
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 32,
    paddingVertical: 30,
    borderRadius: 28,
    backgroundColor: 'rgba(16,19,31,0.92)',
    borderWidth: 1,
    borderColor: 'rgba(240,181,66,0.35)',
    shadowColor: C.amber,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.35,
    shadowRadius: 22,
    elevation: 12,
    minWidth: 300,
  },
  outroHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 4,
  },
  outroStripe: {
    width: 44,
    height: 1,
    backgroundColor: 'rgba(240,181,66,0.5)',
  },
  outroLabel: {
    color: C.amber,
    fontSize: 14,
    fontWeight: '900',
    letterSpacing: 3,
  },
  outroScoreLabel: {
    color: C.t3,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1.4,
    marginTop: 4,
  },
  outroScore: {
    color: C.peach,
    fontSize: 58,
    fontWeight: '900',
    letterSpacing: -1.5,
    lineHeight: 62,
    textShadowColor: 'rgba(224,155,107,0.6)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 18,
  },
  bestRow: {
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: 'rgba(240,181,66,0.10)',
    borderWidth: 1,
    borderColor: 'rgba(240,181,66,0.4)',
    marginVertical: 6,
  },
  bestLabel: {
    color: C.amber,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 1.2,
  },
  bestWord: {
    color: '#FFE8B0',
    fontSize: 22,
    fontWeight: '900',
    letterSpacing: 2,
    textShadowColor: 'rgba(240,181,66,0.6)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 12,
  },
  bestPoints: {
    color: C.peach,
    fontSize: 14,
    fontWeight: '900',
  },
  outroStatsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
    width: '100%',
  },
  outroStat: {
    alignItems: 'center',
    flex: 1,
  },
  outroStatDivider: {
    width: 1,
    height: 30,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  outroStatValue: {
    color: C.t1,
    fontSize: 18,
    fontWeight: '900',
    letterSpacing: -0.3,
  },
  outroStatLabel: {
    color: C.t3,
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 1,
    marginTop: 2,
  },
});
