/**
 * Brain facts pool.
 *
 * Shown as a small card on the home screen, one per day. Selection is
 * day-of-year modulo length, with a recently-shown filter so the same fact
 * doesn't appear twice in 30 days. See `useFactStore.ts`.
 *
 * Tone: human, conversational, slightly surprising. Not clinical. Avoid
 * "studies suggest" — just state the thing if it's well-known.
 */

export interface BrainFact {
  id: string;
  text: string;
}

export const BRAIN_FACTS: BrainFact[] = [
  { id: 'thoughts', text: 'Your brain generates about 70,000 thoughts per day. Most of them are reruns.' },
  { id: 'naps', text: 'Naps between 10 and 20 minutes boost alertness better than coffee.' },
  { id: 'water', text: 'Your brain is 73% water. Even mild dehydration drops your focus noticeably.' },
  { id: 'fiction', text: 'Reading fiction grows empathy. The brain treats imagined social moments like real ones.' },
  { id: 'images', text: 'Your brain can process an image in 13 milliseconds. Faster than a blink.' },
  { id: 'newskill', text: 'Learning a new skill physically changes your brain structure within days.' },
  { id: 'walking', text: 'A 20-minute walk boosts creative thinking by up to 60%.' },
  { id: 'sleep', text: 'Your brain washes itself during deep sleep. Skip it and the trash piles up.' },
  { id: 'forgetting', text: 'Forgetting is a feature, not a bug. It frees up space for what matters.' },
  { id: 'left-right', text: 'The "left-brain / right-brain" split is mostly a myth. Both sides chat constantly.' },
  { id: 'pain', text: 'Your brain feels no pain itself. Brain surgery can be done while you\'re awake.' },
  { id: 'energy', text: 'Your brain uses about 20% of your body\'s energy and weighs only 2% of you.' },
  { id: 'neurons', text: 'You have around 86 billion neurons. Each one talks to thousands of others.' },
  { id: 'memory-feeling', text: 'Memories with strong emotion attached stick around longer. Boring stuff fades.' },
  { id: 'multitasking', text: 'Multitasking is mostly task-switching. You pay a tiny tax every time you switch.' },
  { id: 'breath', text: 'Slow breathing (4 in, 6 out) tells your brain "we\'re safe" — even when you aren\'t.' },
  { id: 'novelty', text: 'Your brain releases dopamine for novelty alone. New routes home count.' },
  { id: 'music', text: 'Listening to music activates almost every part of your brain at once.' },
  { id: 'doodling', text: 'Doodling during meetings actually helps you remember what was said.' },
  { id: 'gratitude', text: 'Writing down three good things each night rewires your default mood over weeks.' },
  { id: 'cold', text: 'Cold exposure spikes norepinephrine — the "wake the heck up" chemical — for hours.' },
  { id: 'eye-contact', text: 'Eye contact synchronizes brain activity between two people. It\'s not just polite.' },
  { id: 'gut', text: 'Your gut has its own nervous system with about 500 million neurons. It really does feel things.' },
  { id: 'language', text: 'Speaking a second language daily delays cognitive decline by an average of 4 years.' },
  { id: 'silence', text: 'Two hours of silence per day grows new cells in the hippocampus — the memory center.' },
  { id: 'handwriting', text: 'Writing notes by hand beats typing for memory. The slowness forces selection.' },
  { id: 'green', text: 'Looking at green for a few minutes reduces mental fatigue. Trees, grass, anything.' },
  { id: 'strangers', text: 'Brief chats with strangers make you measurably happier. Even introverts.' },
  { id: 'morning-light', text: '10 minutes of morning sunlight resets your circadian clock for the whole day.' },
  { id: 'chewing', text: 'Chewing gum increases blood flow to the brain. Test scores go up, slightly.' },
  { id: 'humming', text: 'Humming activates the vagus nerve and calms the nervous system. Try it next time you\'re stressed.' },
  { id: 'mirror', text: 'You have neurons that fire when you watch someone else move. That\'s how mimicry works.' },
  { id: 'memory-place', text: 'Walking through a doorway makes you forget what you walked into the room for. It\'s called the Doorway Effect.' },
  { id: 'practice', text: 'Mentally rehearsing a skill activates many of the same brain areas as actually doing it.' },
  { id: 'sleep-learn', text: 'Studying right before sleep helps the brain encode it more deeply overnight.' },
  { id: 'hunger', text: 'Decision quality drops sharply when you\'re hungry. Big calls? Eat first.' },
  { id: 'novelty-time', text: 'New experiences make time feel longer in memory. Routine days vanish.' },
  { id: 'kindness', text: 'Doing something kind for someone lights up the same brain region as receiving a gift.' },
  { id: 'naps-bigger', text: 'A 90-minute nap gives you a full sleep cycle and can improve memory like a full night.' },
  { id: 'eyes-closed', text: 'Closing your eyes makes you remember details better. Try it during recall.' },
  { id: 'walking-meet', text: 'Walking meetings produce more creative ideas than sitting ones.' },
  { id: 'sigh', text: 'A long sigh is a built-in reset for your nervous system. You do it about every 5 minutes without noticing.' },
  { id: 'novelty-friends', text: 'Having novel experiences with friends bonds you faster than time alone does.' },
  { id: 'meditation', text: '8 weeks of daily meditation thickens the prefrontal cortex — your "decision" area.' },
  { id: 'expectation', text: 'Your brain spends most of its time predicting what comes next. Surprise is what learning feels like.' },
  { id: 'sweet', text: 'Sweetness lights up the same reward circuit as money. Sugar is literally rewarding to think about.' },
  { id: 'emotions-name', text: 'Naming an emotion ("I feel anxious") quiets the part of your brain that\'s producing it.' },
  { id: 'long-term', text: 'Long-term memories aren\'t stored in one place. They\'re reconstructed every time you recall them.' },
  { id: 'rumination', text: 'Worrying about a problem is your brain trying to solve it. The trick is doing it on paper, not in your head.' },
  { id: 'curiosity', text: 'Curiosity itself releases dopamine. Wanting to know is rewarding, even before you know.' },
  { id: 'temperature', text: 'Your brain works best at slightly below body temperature. Cool rooms = sharper thinking.' },
  { id: 'awe', text: 'Looking at vast things — mountains, oceans, stars — shrinks your sense of self and resets stress.' },
  { id: 'tip-tongue', text: 'The "tip of the tongue" feeling is your brain telling you it found the memory but can\'t open it yet.' },
  { id: 'baby', text: 'Babies have more neurons than adults. We prune unused ones as we grow.' },
  { id: 'eyes-up', text: 'Looking up activates a more alert brain state. Looking down does the opposite.' },
  { id: 'plasticity', text: 'Your brain rewires itself every time you learn something. The phrase is neuroplasticity, and it lasts your whole life.' },
  { id: 'walking-blood', text: 'Walking pumps blood to your brain at a rhythm that matches your steps. Roughly 2 Hz.' },
  { id: 'memory-decay', text: 'You forget about half of what you just learned within an hour — unless you actively revisit it.' },
  { id: 'scent', text: 'Smell is the only sense that bypasses the thalamus. It goes straight to memory.' },
  { id: 'overthinking', text: 'Overthinking shrinks the prefrontal cortex over time. Action is good for your brain.' },
  { id: 'novelty-young', text: 'New experiences are why summers felt longer when you were 7. More firsts = more time.' },
  { id: 'comparison', text: 'Comparing yourself to others activates the same brain areas as physical pain. So... maybe don\'t.' },
  { id: 'noise', text: 'Background noise around 70 decibels (a coffee shop) boosts creative output more than silence.' },
  { id: 'placebo', text: 'Placebos work even when you know they\'re placebos. The brain is suggestible.' },
  { id: 'flow', text: 'In flow state, your brain shuts down the self-monitoring region. That\'s why time disappears.' },
  { id: 'language-emo', text: 'Saying "I have to" feels heavier than "I get to." The brain takes the framing literally.' },
  { id: 'social-pain', text: 'Social rejection lights up the same brain region as physical injury. It really does hurt.' },
  { id: 'weight', text: 'Your brain weighs about 1.4 kg — roughly the same as a small cat.' },
  { id: 'storage', text: 'If your brain were a hard drive, it could hold around 2.5 petabytes. That\'s 3 million hours of TV.' },
  { id: 'speed', text: 'Neurons fire at up to 250 mph. Your thoughts are basically lightning made of meat.' },
  { id: 'old', text: 'Adult brains keep growing new neurons in the hippocampus. The "you\'re stuck with what you have" thing is wrong.' },
  { id: 'forget-on-purpose', text: 'The brain actively deletes memories during sleep. Forgetting takes effort too.' },
  { id: 'errors', text: 'Making errors while learning helps the brain remember the right answer better than just being told.' },
  { id: 'worry-future', text: 'About 85% of what people worry about never happens. Of the 15% that does, most people handle it fine.' },
  { id: 'imagination-real', text: 'Your brain can\'t fully tell imagined experiences from real ones. That\'s why visualization works.' },
  { id: 'breakfast', text: 'Skipping breakfast is fine for some people. The "most important meal" thing is mostly marketing.' },
  { id: 'dark-mode', text: 'Reading in low contrast actually improves comprehension. Your brain works a tiny bit harder.' },
  { id: 'caffeine', text: 'Caffeine doesn\'t give you energy. It blocks the chemical that tells you you\'re tired.' },
  { id: 'walking-think', text: 'Most people make their best decisions while walking. Aristotle knew this 2,400 years ago.' },
  { id: 'memory-emotion', text: 'You remember the start and end of an experience more than the middle. It\'s called the peak-end rule.' },
  { id: 'attention-time', text: 'Adult attention span hasn\'t actually shrunk. We just have more interruptions to ignore.' },
  { id: 'novelty-route', text: 'Taking a new route home builds cognitive reserve. Boring commutes are bad for your brain.' },
  { id: 'shower', text: 'Why you get good ideas in the shower: warm water + relaxation + nothing to do = your brain wanders.' },
  { id: 'rest-default', text: 'When your brain "does nothing" it switches to default mode network — where insight and self-reflection happen.' },
  { id: 'sleep-creative', text: 'REM sleep connects unrelated ideas. Most "aha" moments arrive after a good night\'s sleep.' },
  { id: 'face', text: 'You have a brain region just for recognizing faces. It\'s why everyone in a crowd looks like someone you know.' },
  { id: 'fidget', text: 'Fidgeting helps people with active minds focus. It\'s not a flaw, it\'s a strategy.' },
  { id: 'word-tip', text: 'Knowing the first letter of a forgotten word makes you twice as likely to recall it.' },
  { id: 'naps-creative', text: 'Edison and Dali napped holding a metal ball. The clang as it dropped caught their hypnagogic ideas.' },
  { id: 'practice-time', text: '"10,000 hours" is roughly right for elite expertise. For "pretty good" you only need about 20.' },
  { id: 'exercise', text: 'Aerobic exercise grows new brain cells in the memory center. Cardio is brain food.' },
  { id: 'memory-place-2', text: 'You remember things better in the same place you learned them. Hence: study where you\'ll take the test.' },
  { id: 'sleep-debt', text: 'Sleep debt accumulates. One bad night isn\'t much. A bad month dulls everything.' },
  { id: 'novelty-bored', text: 'Boredom is your brain telling you to find something more interesting. It\'s a feature.' },
  { id: 'learning-mistakes', text: 'The brain makes its biggest learning gains right after a mistake — if you pay attention to it.' },
  { id: 'gut-mood', text: '90% of your serotonin is made in your gut. Your stomach really is moody.' },
  { id: 'sleep-amount', text: 'Most adults need 7–9 hours. The "I\'m fine on 5" people are usually just used to feeling tired.' },
  { id: 'novelty-aging', text: 'Doing the same things every day makes years feel shorter. Variety stretches time.' },
  { id: 'belief', text: 'Believing you can change your brain measurably helps you change your brain. It\'s a strange loop.' },
  { id: 'kova', text: 'Like Kova, your brain grows when you tend to it. Skip a few days and it goes a little wild.' },
];
